import { MarketAssetConfig } from "./types";

export const TRACKED_ASSETS: MarketAssetConfig[] = [
  // Top 5 US Stocks
  { symbol: "AAPL", name: "Apple Inc.", category: "US", currencySymbol: "$" },
  { symbol: "MSFT", name: "Microsoft Corp.", category: "US", currencySymbol: "$" },
  { symbol: "NVDA", name: "NVIDIA Corp.", category: "US", currencySymbol: "$" },
  { symbol: "TSLA", name: "Tesla Inc.", category: "US", currencySymbol: "$" },
  { symbol: "META", name: "Meta Platforms Inc.", category: "US", currencySymbol: "$" },

  // Top 5 Crypto
  { symbol: "BTC", name: "Bitcoin", category: "Crypto", currencySymbol: "$" },
  { symbol: "ETH", name: "Ethereum", category: "Crypto", currencySymbol: "$" },
  { symbol: "SOL", name: "Solana", category: "Crypto", currencySymbol: "$" },
  { symbol: "BNB", name: "BNB", category: "Crypto", currencySymbol: "$" },
  { symbol: "DOGE", name: "Dogecoin", category: "Crypto", currencySymbol: "$" },

  // Top 5 ETFs
  { symbol: "SPY", name: "SPDR S&P 500", category: "ETFs", currencySymbol: "$" },
  { symbol: "QQQ", name: "Invesco QQQ", category: "ETFs", currencySymbol: "$" },
  { symbol: "VOO", name: "Vanguard S&P 500", category: "ETFs", currencySymbol: "$" },
  { symbol: "ARKK", name: "ARK Innovation ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "VNQ", name: "Vanguard Real Estate", category: "ETFs", currencySymbol: "$" },
];

const ADDITIONAL_SEARCH_ASSETS: MarketAssetConfig[] = [
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", category: "US", currencySymbol: "$" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C", category: "US", currencySymbol: "$" },
  { symbol: "AMZN", name: "Amazon.com Inc.", category: "US", currencySymbol: "$" },
  { symbol: "NFLX", name: "Netflix Inc.", category: "US", currencySymbol: "$" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", category: "US", currencySymbol: "$" },
  { symbol: "INTC", name: "Intel Corp.", category: "US", currencySymbol: "$" },
  { symbol: "AVGO", name: "Broadcom Inc.", category: "US", currencySymbol: "$" },
  { symbol: "ORCL", name: "Oracle Corp.", category: "US", currencySymbol: "$" },
  { symbol: "CRM", name: "Salesforce Inc.", category: "US", currencySymbol: "$" },
  { symbol: "ADBE", name: "Adobe Inc.", category: "US", currencySymbol: "$" },
  { symbol: "IBM", name: "IBM Corp.", category: "US", currencySymbol: "$" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", category: "US", currencySymbol: "$" },
  { symbol: "QCOM", name: "Qualcomm Inc.", category: "US", currencySymbol: "$" },
  { symbol: "TXN", name: "Texas Instruments Inc.", category: "US", currencySymbol: "$" },
  { symbol: "MU", name: "Micron Technology Inc.", category: "US", currencySymbol: "$" },
  { symbol: "AMAT", name: "Applied Materials Inc.", category: "US", currencySymbol: "$" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", category: "US", currencySymbol: "$" },
  { symbol: "BAC", name: "Bank of America Corp.", category: "US", currencySymbol: "$" },
  { symbol: "WFC", name: "Wells Fargo & Co.", category: "US", currencySymbol: "$" },
  { symbol: "GS", name: "Goldman Sachs Group Inc.", category: "US", currencySymbol: "$" },
  { symbol: "MS", name: "Morgan Stanley", category: "US", currencySymbol: "$" },
  { symbol: "C", name: "Citigroup Inc.", category: "US", currencySymbol: "$" },
  { symbol: "V", name: "Visa Inc.", category: "US", currencySymbol: "$" },
  { symbol: "MA", name: "Mastercard Inc.", category: "US", currencySymbol: "$" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", category: "US", currencySymbol: "$" },
  { symbol: "COIN", name: "Coinbase Global Inc.", category: "US", currencySymbol: "$" },
  { symbol: "HOOD", name: "Robinhood Markets Inc.", category: "US", currencySymbol: "$" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", category: "US", currencySymbol: "$" },
  { symbol: "LLY", name: "Eli Lilly and Co.", category: "US", currencySymbol: "$" },
  { symbol: "JNJ", name: "Johnson & Johnson", category: "US", currencySymbol: "$" },
  { symbol: "PFE", name: "Pfizer Inc.", category: "US", currencySymbol: "$" },
  { symbol: "ABBV", name: "AbbVie Inc.", category: "US", currencySymbol: "$" },
  { symbol: "MRK", name: "Merck & Co. Inc.", category: "US", currencySymbol: "$" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", category: "US", currencySymbol: "$" },
  { symbol: "WMT", name: "Walmart Inc.", category: "US", currencySymbol: "$" },
  { symbol: "COST", name: "Costco Wholesale Corp.", category: "US", currencySymbol: "$" },
  { symbol: "HD", name: "Home Depot Inc.", category: "US", currencySymbol: "$" },
  { symbol: "MCD", name: "McDonald's Corp.", category: "US", currencySymbol: "$" },
  { symbol: "NKE", name: "Nike Inc.", category: "US", currencySymbol: "$" },
  { symbol: "SBUX", name: "Starbucks Corp.", category: "US", currencySymbol: "$" },
  { symbol: "DIS", name: "Walt Disney Co.", category: "US", currencySymbol: "$" },
  { symbol: "XOM", name: "Exxon Mobil Corp.", category: "US", currencySymbol: "$" },
  { symbol: "CVX", name: "Chevron Corp.", category: "US", currencySymbol: "$" },
  { symbol: "COP", name: "ConocoPhillips", category: "US", currencySymbol: "$" },
  { symbol: "BA", name: "Boeing Co.", category: "US", currencySymbol: "$" },
  { symbol: "CAT", name: "Caterpillar Inc.", category: "US", currencySymbol: "$" },
  { symbol: "GE", name: "GE Aerospace", category: "US", currencySymbol: "$" },
  { symbol: "DE", name: "Deere & Co.", category: "US", currencySymbol: "$" },
  { symbol: "RIVN", name: "Rivian Automotive Inc.", category: "US", currencySymbol: "$" },
  { symbol: "LCID", name: "Lucid Group Inc.", category: "US", currencySymbol: "$" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "VUG", name: "Vanguard Growth ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "VTV", name: "Vanguard Value ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "SCHD", name: "Schwab US Dividend Equity ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLK", name: "Technology Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLF", name: "Financial Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLE", name: "Energy Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLU", name: "Utilities Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR Fund", category: "ETFs", currencySymbol: "$" },
  { symbol: "GLD", name: "SPDR Gold Shares", category: "ETFs", currencySymbol: "$" },
  { symbol: "SLV", name: "iShares Silver Trust", category: "ETFs", currencySymbol: "$" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", category: "ETFs", currencySymbol: "$" },
  { symbol: "USDT", name: "Tether", category: "Crypto", currencySymbol: "$" },
  { symbol: "USDC", name: "USD Coin", category: "Crypto", currencySymbol: "$" },
  { symbol: "XRP", name: "XRP", category: "Crypto", currencySymbol: "$" },
  { symbol: "ADA", name: "Cardano", category: "Crypto", currencySymbol: "$" },
  { symbol: "AVAX", name: "Avalanche", category: "Crypto", currencySymbol: "$" },
  { symbol: "DOT", name: "Polkadot", category: "Crypto", currencySymbol: "$" },
  { symbol: "TRX", name: "TRON", category: "Crypto", currencySymbol: "$" },
  { symbol: "LINK", name: "Chainlink", category: "Crypto", currencySymbol: "$" },
  { symbol: "MATIC", name: "Polygon", category: "Crypto", currencySymbol: "$" },
  { symbol: "TON", name: "Toncoin", category: "Crypto", currencySymbol: "$" },
  { symbol: "SHIB", name: "Shiba Inu", category: "Crypto", currencySymbol: "$" },
  { symbol: "LTC", name: "Litecoin", category: "Crypto", currencySymbol: "$" },
  { symbol: "BCH", name: "Bitcoin Cash", category: "Crypto", currencySymbol: "$" },
  { symbol: "UNI", name: "Uniswap", category: "Crypto", currencySymbol: "$" },
  { symbol: "ATOM", name: "Cosmos", category: "Crypto", currencySymbol: "$" }
];

const seenSymbols = new Set<string>();

export const SEARCHABLE_ASSETS: MarketAssetConfig[] = [
  ...TRACKED_ASSETS,
  ...ADDITIONAL_SEARCH_ASSETS
].filter((asset) => {
  if (seenSymbols.has(asset.symbol)) return false;
  seenSymbols.add(asset.symbol);
  return true;
});
